version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    networks:
      - tradeforge-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build: ./backend
    command: >
      bash -c "
        ./prestart.sh &&
        uvicorn main:app --host 0.0.0.0 --port 8000
      "
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tradeforge-network
    environment:
      - POSTGRES_SERVER=postgres
    env_file:
      - ./backend/.env

  # Frontend application
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - tradeforge-network
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api

networks:
  tradeforge-network:
    driver: bridge

volumes:
  postgres_data: 