apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://10.10.0.8:9090
    isDefault: true
    version: 1
    editable: false
    jsonData:
      httpMethod: GET
      timeInterval: 15s
      queryTimeout: 60s
